repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.1.6
    hooks:
      # Run the linter.
      - id: ruff
        args: [ --fix ]
      # Run the formatter.
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1  # Use the specific version of isort you want
    hooks:
      - id: isort
        args: ['--profile', 'black']  # Optional: if you want isort to be compatible with ruff formatting

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910  # Use the specific version of mypy you want
    hooks:
      - id: mypy
        additional_dependencies: [types-requests]  # Optional: add any additional typing libraries you need

